#!/usr/bin/env node

/**
 * cold-start/scripts/init-mb.js
 *
 * A small helper to initialize the Memory Bank skeleton in the current directory.
 *
 * - Creates .memory-bank/ (durable knowledge base)
 * - Creates .tasks/ (operational runtime memory)
 * - Creates .protocols/ (file-based protocols)
 * - Creates AGENTS.md + CLAUDE.md symlink/copy
 *
 * Safe by default: does NOT overwrite existing files.
 *
 * Update mode:
 * - --sync / --force: overwrite generated command specs in .memory-bank/commands/
 *   and proxy skills in .claude/skills/ + .agents/skills/ (keeps other docs safe).
 */

const fs = require('fs');
const path = require('path');

const ROOT = process.cwd();
const MB = '.memory-bank';
const SHARED_DIR = path.resolve(__dirname, '..');
const REFERENCES_DIR = path.join(SHARED_DIR, 'references');
const COMMAND_TEMPLATES_DIR = path.join(REFERENCES_DIR, 'commands');
const WORKFLOW_REFERENCES_DIR = path.join(REFERENCES_DIR, 'workflows');
const FLAT_COMMAND_PREFIX = 'shared-commands-';
const RUNTIME_SCRIPT_ASSETS = [
  { asset: 'mb-lint.mjs', target: 'scripts/mb-lint.mjs' },
  { asset: 'mb-doctor.mjs', target: 'scripts/mb-doctor.mjs' },
];

const ARGS = new Set(process.argv.slice(2));
const SYNC_MODE = ARGS.has('--sync') || ARGS.has('--force');
const TODAY = new Date().toISOString().slice(0, 10);
const GENERATED_MARKER = '<!-- Generated by memobank init-mb.js. Safe to overwrite with init-mb.js --sync. -->';
const LEGACY_ALIAS_COMMANDS = new Set([
  'find-skill',
  'mb-execute',
  'mb-from-prd',
  'mb-map-codebase',
  'mb-red-verify',
  'mb-review',
  'mb-verify',
]);

const TASK_SCHEMA = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  title: 'Memory Bank Task Record',
  type: 'object',
  additionalProperties: false,
  required: [
    'id',
    'title',
    'status',
    'wave',
    'feature',
    'reqs',
    'depends_on',
    'touched_files',
    'tier',
    'gates',
    'verify',
    'docs',
    'evidence_required',
    'source_artifacts',
    'normative_inputs',
    'constraints',
    'invariants',
    'verification_targets',
  ],
  properties: {
    id: { type: 'string', pattern: '^TASK-[0-9]{3,}$' },
    title: { type: 'string' },
    status: {
      type: 'string',
      enum: ['planned', 'ready', 'in_progress', 'blocked', 'done', 'failed'],
    },
    wave: { type: 'string' },
    feature: { type: 'string' },
    reqs: { type: 'array', items: { type: 'string' } },
    depends_on: { type: 'array', items: { type: 'string' } },
    touched_files: { type: 'array', items: { type: 'string' } },
    tier: { type: 'string', enum: ['T0', 'T1', 'T2', 'T3'] },
    gates: {
      type: 'array',
      items: {
        type: 'object',
        required: ['name', 'command', 'required'],
        properties: {
          name: { type: 'string' },
          command: { type: 'string' },
          required: { type: 'boolean' },
        },
      },
    },
    verify: {
      type: 'array',
      items: {
        anyOf: [
          { type: 'string' },
          { type: 'object', additionalProperties: true },
        ],
      },
    },
    docs: { type: 'array', items: { type: 'string' } },
    evidence_required: { type: 'array', items: { type: 'string' } },
    source_artifacts: { type: 'array', items: { type: 'string' } },
    normative_inputs: { type: 'array', items: { type: 'string' } },
    constraints: { type: 'array', items: { type: 'string' } },
    invariants: { type: 'array', items: { type: 'string' } },
    verification_targets: { type: 'array', items: { type: 'string' } },
  },
};

const TASK_INDEX = {
  version: 1,
  tasks: [],
};

if (ARGS.has('--help') || ARGS.has('-h')) {
  console.log(`
init-mb.js — initialize Memory Bank skeleton

Usage:
  node init-mb.js                # safe (no overwrites)
  node init-mb.js --sync         # update .memory-bank/commands + proxy skills
  node init-mb.js --force        # same behavior as --sync
`.trim());
  process.exit(0);
}

if (SYNC_MODE) {
  console.log('\n[Mode] SYNC: updating generated commands/proxy skills/runtime scripts; obsolete unmarked artifacts are warned only.');
}

function ensureDir(rel) {
  const p = path.join(ROOT, rel);
  if (!fs.existsSync(p)) {
    fs.mkdirSync(p, { recursive: true });
    console.log(`  + ${rel}/`);
  }
}

function writeFile(rel, content, { overwrite = false } = {}) {
  const p = path.join(ROOT, rel);
  const existed = fs.existsSync(p);
  if (existed && !overwrite) {
    if (SYNC_MODE && rel === 'AGENTS.md') {
      const current = fs.readFileSync(p, 'utf8');
      if (!isGeneratedAgentsGuide(current)) {
        console.log(`  ! ${rel} exists but is not recognized as generated; left unchanged`);
        return;
      }
      overwrite = true;
    } else {
      return;
    }
  }

  fs.writeFileSync(p, content, 'utf8');
  console.log(`  ${existed ? '~' : '+'} ${rel}${existed ? ' (updated)' : ''}`);
}

function readUtf8(absPath) {
  return fs.readFileSync(absPath, 'utf8');
}

function listMarkdownFiles(absDir) {
  return fs
    .readdirSync(absDir, { withFileTypes: true })
    .filter((d) => d.isFile())
    .map((d) => d.name)
    .filter((name) => name.toLowerCase().endsWith('.md'))
    .sort((a, b) => a.localeCompare(b));
}

function resolveCommandTemplates() {
  if (fs.existsSync(COMMAND_TEMPLATES_DIR)) {
    return listMarkdownFiles(COMMAND_TEMPLATES_DIR).map((filename) => ({
      name: filename.replace(/\.md$/i, ''),
      absPath: path.join(COMMAND_TEMPLATES_DIR, filename),
      filename,
    }));
  }

  if (!fs.existsSync(REFERENCES_DIR)) return [];

  return listMarkdownFiles(REFERENCES_DIR)
    .filter((filename) => filename.startsWith(FLAT_COMMAND_PREFIX))
    .map((filename) => ({
      name: filename.replace(new RegExp(`^${FLAT_COMMAND_PREFIX}`), '').replace(/\.md$/i, ''),
      absPath: path.join(REFERENCES_DIR, filename),
      filename: `${filename.replace(new RegExp(`^${FLAT_COMMAND_PREFIX}`), '')}`,
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

function resolveReferenceFile(category, filename) {
  const nestedPath = path.join(REFERENCES_DIR, category, filename);
  if (fs.existsSync(nestedPath)) return nestedPath;

  const flattenedPath = path.join(REFERENCES_DIR, `shared-${category}-${filename}`);
  if (fs.existsSync(flattenedPath)) return flattenedPath;

  return null;
}

function resolveRuntimeAsset(filename) {
  const candidates = [
    // Source layout: skills/_shared/scripts/init-mb.js -> skills/mb-garden/assets
    // Installed layout: .agents/skills/mb-init/scripts/shared-init-mb.js -> sibling mb-garden/assets
    path.join(SHARED_DIR, '..', 'mb-garden', 'assets', filename),
    path.join(SHARED_DIR, 'assets', filename),
  ];

  return candidates.find((candidate) => fs.existsSync(candidate)) || null;
}

function copyRuntimeScript(asset, target) {
  const absPath = resolveRuntimeAsset(asset);
  if (!absPath) {
    console.error(`\nERROR: Runtime script asset not found: ${asset}`);
    console.error('Run init-mb.js from the memobank_BMAD_SDD package with mb-garden installed alongside mb-init.');
    process.exit(1);
  }

  writeFile(target, readUtf8(absPath), { overwrite: SYNC_MODE });
}

function copyRuntimeScripts() {
  RUNTIME_SCRIPT_ASSETS.forEach(({ asset, target }) => copyRuntimeScript(asset, target));
}

function copyWorkflowReference(filename) {
  const absPath = resolveReferenceFile('workflows', filename);
  if (!absPath) {
    console.error(`\nERROR: Workflow reference not found: ${path.join(WORKFLOW_REFERENCES_DIR, filename)} or flattened shared-workflows-${filename}.`);
    console.error('Run init-mb.js from the memobank_BMAD_SDD package (do not copy it standalone).');
    process.exit(1);
  }

  writeFile(`${MB}/workflows/${filename}`, readUtf8(absPath), { overwrite: SYNC_MODE });
}

function extractFrontmatterDescription(markdown) {
  const fm = markdown.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n/);
  if (!fm) return null;
  const m = fm[1].match(/^description:\s*(.*)\s*$/m);
  if (!m) return null;
  const value = m[1].trim();
  if (!value) return null;
  return value.replace(/^"(.*)"$/, '$1').replace(/^'(.*)'$/, '$1');
}

function yamlQuote(value) {
  const escaped = String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `"${escaped}"`;
}

function addGeneratedMarker(markdown) {
  if (markdown.includes(GENERATED_MARKER)) return markdown;

  const frontmatter = markdown.match(/^(---\r?\n[\s\S]*?\r?\n---\r?\n?)/);
  if (frontmatter) {
    return `${frontmatter[1]}${GENERATED_MARKER}\n${markdown.slice(frontmatter[1].length)}`;
  }

  return `${GENERATED_MARKER}\n${markdown}`;
}

function hasGeneratedMarker(content) {
  return content.includes(GENERATED_MARKER);
}

function isGeneratedAgentsGuide(content) {
  const normalized = content.replace(/\r\n/g, '\n');
  return hasGeneratedMarker(normalized) || (
    normalized.startsWith('# Agent Operating Guide (Project Map)\n') &&
    normalized.includes('## Runtime vs durable memory') &&
    normalized.includes('## Entry points')
  );
}

function isGeneratedProxySkill(content, expectedName = null) {
  const normalized = content.replace(/\r\n/g, '\n').trim();
  if (hasGeneratedMarker(normalized)) return true;

  const proxy = normalized.match(/^---\n[\s\S]*?\n---\n\nRead and follow the instructions in `\.memory-bank\/commands\/([^`]+)\.md`$/);
  if (!proxy) return false;

  return expectedName === null || proxy[1] === expectedName;
}

function escapeRegExp(value) {
  return String(value).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function isLegacyAliasCommandSpec(filename, content) {
  const name = filename.replace(/\.md$/i, '');
  if (!LEGACY_ALIAS_COMMANDS.has(name)) return false;

  const normalized = content.replace(/\r\n/g, '\n');
  const aliasHeading = new RegExp(`^#\\s+/${escapeRegExp(name)}\\s+[—-]\\s+Alias\\b`, 'm');
  return aliasHeading.test(normalized) || /^description:\s*.*(Alias|Алиас)/im.test(normalized);
}

function removePath(rel) {
  fs.rmSync(path.join(ROOT, rel), { recursive: true, force: true });
  console.log(`  - ${rel}`);
}

function cleanupGeneratedCommandSpecs(expectedFilenames) {
  if (!SYNC_MODE) return;

  const relDir = `${MB}/commands`;
  const absDir = path.join(ROOT, relDir);
  if (!fs.existsSync(absDir)) return;

  listMarkdownFiles(absDir).forEach((filename) => {
    if (expectedFilenames.has(filename)) return;

    const rel = `${relDir}/${filename}`;
    const content = readUtf8(path.join(absDir, filename));
    if (hasGeneratedMarker(content)) {
      removePath(rel);
      return;
    }

    const legacyNote = isLegacyAliasCommandSpec(filename, content) ? ' legacy alias' : '';
    console.log(`  ! ${rel} is obsolete${legacyNote} but not marked as generated; left unchanged`);
  });
}

function cleanupGeneratedProxySkills(runtimeRoot, expectedNames) {
  if (!SYNC_MODE) return;

  const absRoot = path.join(ROOT, runtimeRoot);
  if (!fs.existsSync(absRoot)) return;

  fs.readdirSync(absRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .forEach((entry) => {
      if (expectedNames.has(entry.name)) return;

      const relSkill = `${runtimeRoot}/${entry.name}`;
      const relSkillFile = `${relSkill}/SKILL.md`;
      const absSkillFile = path.join(ROOT, relSkillFile);
      if (!fs.existsSync(absSkillFile)) {
        console.log(`  ! ${relSkill} is obsolete but has no generated SKILL.md marker; left unchanged`);
        return;
      }

      const skillContent = readUtf8(absSkillFile);
      if (hasGeneratedMarker(skillContent)) {
        removePath(relSkill);
        return;
      }

      const proxyNote = isGeneratedProxySkill(skillContent, entry.name) ? ' generated-looking proxy' : '';
      console.log(`  ! ${relSkill} is obsolete${proxyNote} but not marked as generated; left unchanged`);
    });
}

function generateCommandsIndex(commandMetas) {
  const lines = [];
  lines.push('---');
  lines.push('description: Роутер по command-spec файлам (slash commands).');
  lines.push('status: active');
  lines.push('---');
  lines.push('# Commands');
  lines.push('');
  commandMetas.forEach(({ name, desc }) => {
    lines.push(`- [.memory-bank/commands/${name}.md](${name}.md): ${desc}`);
  });
  lines.push('');
  return lines.join('\n');
}

function seedCommandsFromTemplates() {
  const templates = resolveCommandTemplates()
    .filter(({ name }) => !LEGACY_ALIAS_COMMANDS.has(name));
  if (templates.length === 0) {
    console.error(`\nERROR: Command templates not found in: ${COMMAND_TEMPLATES_DIR} or flattened references.`);
    console.error('Run init-mb.js from the memobank_BMAD_SDD package (do not copy it standalone).');
    process.exit(1);
  }

  const expectedFilenames = new Set(templates.map(({ filename }) => filename));
  expectedFilenames.add('constitution.md');
  expectedFilenames.add('index.md');
  cleanupGeneratedCommandSpecs(expectedFilenames);

  const metas = [];

  templates.forEach(({ filename, absPath, name }) => {
    const content = readUtf8(absPath);
    const desc = extractFrontmatterDescription(content) || `/${name}`;

    writeFile(`${MB}/commands/${filename}`, addGeneratedMarker(content), { overwrite: SYNC_MODE });
    metas.push({ name, desc });
  });

  if (!metas.some(({ name }) => name === 'constitution')) {
    writeFile(`${MB}/commands/constitution.md`, addGeneratedMarker(constitutionCommandTemplate()), { overwrite: SYNC_MODE });
    metas.push({ name: 'constitution', desc: 'Read or minimally amend the Project Constitution.' });
    metas.sort((a, b) => a.name.localeCompare(b.name));
  }

  writeFile(`${MB}/commands/index.md`, addGeneratedMarker(generateCommandsIndex(metas)), { overwrite: SYNC_MODE });
  return metas;
}

function constitutionCommandTemplate() {
  return `---
description: Run a contextual interview and maintain the Project Constitution.
status: active
---
# /constitution

## Purpose
Run a contextual governing-principles interview and maintain \`.memory-bank/constitution.md\`.

## Behavior
1. Read \`.memory-bank/constitution.md\`.
2. Read \`.memory-bank/analysis/product-brief.md\` when present and use it only to make questions contextual.
3. If \`.memory-bank/constitution.md\` is missing, create it from the generated Constitution skeleton.
4. Read governance context before amendments:
   - \`.memory-bank/mbb/index.md\`
   - \`.memory-bank/spec-index.md\`
   - \`.memory-bank/invariants.md\`
   - \`.memory-bank/workflows/*\`
   - \`AGENTS.md\`
5. Ask at most 5 questions per pass, one at a time, using recommended options/rationale like \`/write-prd\`.
6. Cover project level, architecture priority, DoD/checks, agent autonomy/human checkpoints, and critical non-negotiables.
7. If the user skips, leave \`project_principles: framework-default\` or set \`project_principles: skipped\`, keep \`ratified: null\`, and continue; this is not a hard blocker.
8. When project principles become \`ratified\` or \`partial\`, set \`ratified: YYYY-MM-DD\`.
9. Keep it short; move concrete project rules to \`invariants.md\`, \`contracts/*\`, \`states/*\`, or workflow policy docs.
10. Do not invent domain-specific principles without evidence.
11. Do not add \`/mb-constitution\`, Spec Kit hooks, migration tooling, governance engines, or compatibility layers.
`;
}

function symlinkOrCopy(target, linkName) {
  const linkPath = path.join(ROOT, linkName);
  if (fs.existsSync(linkPath)) return;

  try {
    fs.symlinkSync(target, linkPath);
    console.log(`  ~ ${linkName} -> ${target}`);
  } catch (e) {
    // Windows / restricted env fallback
    const targetPath = path.join(ROOT, target);
    if (fs.existsSync(targetPath)) {
      fs.writeFileSync(linkPath, fs.readFileSync(targetPath, 'utf8'));
      console.log(`  + ${linkName} (copy, symlink failed)`);
    } else {
      console.log(`  ! Could not create ${linkName}: missing target ${target}`);
    }
  }
}

console.log('\n[1/5] Creating directories...');
[
  MB,
  `${MB}/mbb`,
  `${MB}/architecture`,
  `${MB}/guides`,
  `${MB}/adrs`,
  `${MB}/tech-specs`,
  `${MB}/domains`,
  `${MB}/contracts`,
  `${MB}/states`,
  `${MB}/runbooks`,
  `${MB}/workflows`,
  `${MB}/quality`,
  `${MB}/testing`,
  `${MB}/skills`,
  `${MB}/epics`,
  `${MB}/features`,
  `${MB}/schemas`,
  `${MB}/tasks`,
  `${MB}/tasks/plans`,
  `${MB}/commands`,
  `${MB}/agents`,
  `${MB}/archive`,
  `${MB}/bugs`,
  'scripts',
  '.tasks',
  '.protocols',
].forEach(ensureDir);

console.log('\n[2/5] Writing core files...');

writeFile('AGENTS.md', `# Agent Operating Guide (Project Map)
${GENERATED_MARKER}

## Prime before work
1. Read \`AGENTS.md\` (this guide)
2. Read \`.memory-bank/constitution.md\` (top governing policy)
3. Read \`.memory-bank/mbb/index.md\` (Memory Bank rules)
4. Read \`.memory-bank/spec-index.md\` (normative routing)
5. Read \`.memory-bank/index.md\` (table of contents)
6. Read task/feature-specific docs

## Orchestrator Mode

If no explicit role is given to the top-level agent, act as:

ROLE: ORCHESTRATOR

Delegated agents are not ORCHESTRATOR by default.
The role is fixed and cannot be changed.
Every ORCHESTRATOR response must start with:
\`Роль: Оркестратор\`

### Core Rules
- ORCHESTRATOR is responsible for strategy, scope, planning, coordination, risk control, consultation with user and final judgment.
- ORCHESTRATOR must follow Spec Before Code.
- Before any non-trivial code/workflow/CI/test/docs/package/config/skill change, ORCHESTRATOR must identify affected specs/source-of-truth, check match, report conflicts/gaps/unclear requirements/risks, and propose spec/source-of-truth changes before implementation if needed.
- If there is no spec layer, identify closest source of truth first: README, docs, existing code, tests, config, or project conventions.
- Keep the Project Constitution early in priming, but do not turn AGENTS.md into Constitution.
- Use the current JSON task registry: \`.memory-bank/tasks/index.json\` and indexed \`.memory-bank/tasks/TASK-*.task.json\` records.
- Route work by \`task.tier: T0|T1|T2|T3\`.
- Do not use legacy task models.
- Run \`node scripts/mb-lint.mjs\` and \`/mb-doctor\` where task records or Memory Bank routing change.
- Run \`/mb-doctor --strict\` before autonomous/autopilot task selection.

### Delegation
- ORCHESTRATOR delegates implementation, tests, verification, and review to subagents.
- ORCHESTRATOR may delegate research, inspection, and context gathering to preserve context window.
- Each delegated task must have clear role, task, scope, and expected result.
- Each delegated task must instruct the subagent to stop and report blockers, scope conflicts, risky side effects, unclear requirements, or contradictions with specs/source-of-truth artifacts.
- Do not run parallel subagents when their scopes, files, or responsibilities may overlap.
- ORCHESTRATOR waits for required subagent results before continuing.
- Receive subagent reports, detect conflicts, gaps, and risks, then decide next steps.

### Allowed
- Read key documents for task understanding.
- Create plans, decomposition, risk notes, and scope boundaries.
- Create or update planning artifacts when the task permits them.
- Run read-only checks needed for judgment.
- Launch subagents for search, analysis, implementation, tests, and review.
- Report status, decisions, blockers, and required user input.

### Forbidden
- Do not directly modify code, tests, CI, scripts, docs, workflow, skills, package files, or configs unless the user explicitly permits ORCHESTRATOR implementation.
- Do not perform implementation work.
- Do not silently fix reviewed work; delegate fixes back to an appropriate subagent.
- Do not skip Spec Before Code for non-trivial changes.

## Preferred context routing
- Start with \`.memory-bank/architecture/*\` and \`.memory-bank/guides/*\` for concept priming.
- If present, prefer explicit normative docs such as \`.memory-bank/constitution.md\`, \`.memory-bank/spec-index.md\`, \`.memory-bank/invariants.md\`, \`.memory-bank/glossary.md\`, \`.memory-bank/contracts/*\`, \`.memory-bank/states/*\`, \`.memory-bank/runbooks/*\`, and \`.memory-bank/testing/*\`.
- Normative docs enrich the Memory Bank; they do not invalidate valid duo docs.
- Before serious work, read \`.memory-bank/spec-index.md\` and follow linked SDD specs.
- Do not create a new spec before checking existing specs through \`.memory-bank/spec-index.md\`.
- For \`T2\` / \`T3\` tasks, linked SDD specs are normative inputs; missing linked specs are a blocker for serious work.

## Docs First
After finishing a meaningful unit of work:
1) Update \`.memory-bank/\` (WHY/WHERE + navigation)
2) Then commit code changes

## Runtime vs durable memory
- Durable knowledge base: \`.memory-bank/\`
- Operational artifacts: \`.tasks/\` (NOT part of Memory Bank)
- Long-running plans/logs: \`.protocols/\`

## Where skills live (don’t confuse)
- Codex CLI reads project skills from \`.agents/skills/<name>/SKILL.md\` (not from \`.codex/\`).
- Claude Code reads project skills from \`.claude/skills/<name>/SKILL.md\`.
- \`.codex/\` is only for project configuration (e.g. \`.codex/config.toml\`).

## Subagents
- Orchestrator → workers only (max depth = 2)
- Workers write details into \`.tasks/TASK-XXX/\`
- Orchestrator reads only short summaries

## Worker execution guardrails
- Workers read assigned protocol files and relevant specs before acting.
- Workers stay inside scope from \`.protocols/TASK-<ID>/context.md\` and \`.protocols/TASK-<ID>/plan.md\`.
- Workers keep \`.protocols/TASK-<ID>/progress.md\` updated.
- Workers report blockers, scope conflicts, and spec contradictions instead of expanding scope.
- Workers do not make product, spec, architecture, safety, or public-contract decisions.
- Detailed reports go to \`.tasks/TASK-<ID>/\`.
- Report names follow \`TASK-<ID>-S-<STAGE>-final-report-<code|docs>-<NN>.md\`.
- Apply KISS and Spec Before Code.

## Clean context (recommended)
- Route each \`TASK-XXX\` by \`task.tier\` and \`.memory-bank/workflows/tier-policy.md\`.
- T0/T1 may use compact \`.protocols/TASK-XXX/run.md\`; compact evidence can be enough.
- Scheduler mode: T2/T3 require full protocol state plus \`/verify\` PASS and \`/red-verify\` semantic-pass before scheduler marks done.
- Manual mode: \`/verify\` PASS may close; \`/red-verify\` may run later and reopen/block/fail.
- T3 also requires a human-aware checkpoint and rollback/recovery note.
- If running in **Claude Code**: execute each \`TASK-XXX\` in a **fresh Claude session** using tier-appropriate \`.protocols/TASK-XXX/\` state.
- If running in **Codex**: you can run each \`TASK-XXX\` in a fresh session via \`codex exec\` (see \`/execute\`).
- Sequencing: independent tasks may run in parallel clean sessions; dependent/shared-file tasks must run sequentially.

Codex (fresh session):
- \`codex exec --ephemeral --full-auto -m gpt-5.2-high 'TASK_ID=TASK-123. Read AGENTS.md + task record + tier-policy. Use tier-appropriate .protocols/TASK-123/ state. Implement. Record evidence. Report → .tasks/TASK-123/…'\`

Claude (fresh session):
- \`claude -p --no-session-persistence --permission-mode acceptEdits --model opus 'TASK_ID=TASK-123. Read AGENTS.md + task record + tier-policy. Use tier-appropriate .protocols/TASK-123/ state. Implement. Record evidence. Report → .tasks/TASK-123/…'\`

## Two modes (interactive vs autonomous)
- **Interactive**: target chain is \`/analysis -> /brief -> /constitution if project_principles is not ratified|partial -> /write-prd -> /spec-init -> /prd -> optional /spec-backbone -> /spec-design FT-001 -> /prd-to-tasks FT-001 -> /execute TASK-001 -> /verify TASK-001 -> /red-verify TASK-001 for T2/T3 -> /mb-sync\`.
- Use \`/spec-backbone\` after \`/prd\` when the feature set exposes shared T2/T3 backbone concerns; it does not replace per-feature \`/spec-design FT-001\`.
- Use \`/brainstorm\` before \`/brief\` only when the idea is raw.
- Use \`/clarify-feature FT-001\` only for explicit feature blockers before \`/prd-to-tasks\`.
- **Autonomous (batch)**: use \`/autonomous\` for full \`PRD → done\`; it runs \`/spec-auto --init\` after \`/write-prd\` and \`/spec-auto --all\` after \`/prd\`. Use \`/autopilot\` only if JSON task records and required SDD spec links already exist. See: \`.memory-bank/workflows/execute-loop.md\` and \`.memory-bank/workflows/autonomy-policy.md\`.

Naming:
- Folder: \`.tasks/TASK-<ID>/\`
- Files: \`TASK-<ID>-S-<STAGE>-final-report-<code|docs>-<NN>.md\`

## Quality gates (before merge)
- \`node scripts/mb-lint.mjs\` / typecheck / build
- \`/mb-doctor\` (strict before autonomous/autopilot task selection)
- unit tests
- e2e tests (if UI/flow)

## Entry points
- /cold-start → .memory-bank/commands/cold-start.md
- /mb → .memory-bank/commands/mb.md
- /mb-init → .memory-bank/commands/mb-init.md
- /constitution → .memory-bank/commands/constitution.md (normal before /write-prd only when project_principles is not ratified|partial)
- /analysis → .memory-bank/commands/analysis.md (optional idea discovery router)
- /brainstorm → .memory-bank/commands/brainstorm.md (optional raw idea facilitation)
- /brief → .memory-bank/commands/brief.md (optional product brief before PRD)
- /write-prd → .memory-bank/commands/write-prd.md
- /spec-init → .memory-bank/commands/spec-init.md
- /prd → .memory-bank/commands/prd.md
- /spec-backbone → .memory-bank/commands/spec-backbone.md (optional after /prd for shared T2/T3 backbone design)
- /spec-design → .memory-bank/commands/spec-design.md
- /spec-auto → .memory-bank/commands/spec-auto.md
- /clarify-feature → .memory-bank/commands/clarify-feature.md
- /prd-to-tasks → .memory-bank/commands/prd-to-tasks.md
- /execute → .memory-bank/commands/execute.md
- /verify → .memory-bank/commands/verify.md
- /red-verify → .memory-bank/commands/red-verify.md
- /mb-doctor → .memory-bank/commands/mb-doctor.md
- /autopilot → .memory-bank/commands/autopilot.md
- /autonomous → .memory-bank/commands/autonomous.md
- /map-codebase → .memory-bank/commands/map-codebase.md
- /mb-sync → .memory-bank/commands/mb-sync.md
- /discuss → .memory-bank/commands/discuss.md
- /add-tests → .memory-bank/commands/add-tests.md
- /review → .memory-bank/commands/review.md
- /mb-garden → .memory-bank/commands/mb-garden.md
- /mb-harness → .memory-bank/commands/mb-harness.md
`);

writeFile(`${MB}/index.md`, `---
description: Главная карта знаний проекта (table of contents) для агентов.
status: active
---
# Memory Bank Index

## Навигация

- [.memory-bank/constitution.md](constitution.md): Project Constitution — top governing policy for agents.
- [.memory-bank/mbb/index.md](mbb/index.md): Правила ведения Memory Bank (MBB).
- [.memory-bank/product.md](product.md): Продукт (C4 L1).
- [.memory-bank/requirements.md](requirements.md): Требования + RTM.
- [.memory-bank/epics/](epics/): Эпики (C4 L2).
- [.memory-bank/features/](features/): Фичи (C4 L3).
- [.memory-bank/tasks/index.json](tasks/index.json): Authoritative JSON task record index.
- [.memory-bank/schemas/task.schema.json](schemas/task.schema.json): JSON schema for task records.
- [.memory-bank/workflows/tier-policy.md](workflows/tier-policy.md): Tier policy for TASK routing and protocol depth.

- [.memory-bank/spec-index.md](spec-index.md): SDD Design Specs Index and source-of-truth route map.
- [.memory-bank/glossary.md](glossary.md): Общий словарь терминов и доменных значений.
- [.memory-bank/invariants.md](invariants.md): Глобальные MUST/NEVER правила.
- [.memory-bank/architecture/](architecture/): Duo + boundaries (WHAT/WHY).
- [.memory-bank/guides/](guides/): Valid HOW docs для использования, запуска и troubleshooting.
- [.memory-bank/adrs/](adrs/): ADR решения.

- [.memory-bank/contracts/](contracts/): Контракты и boundary specs (prefer when present).
- [.memory-bank/states/](states/): Lifecycle/state rules (prefer when present).
- [.memory-bank/runbooks/](runbooks/): Runbooks и operational procedures.
- [.memory-bank/testing/index.md](testing/index.md): Testing strategy.
- [.memory-bank/skills/index.md](skills/index.md): Skill registry.
`);

writeFile(`${MB}/mbb/index.md`, `---
description: Memory Bank Bible — правила, инварианты и стандарты документации.
status: active
---
# Memory Bank Bible (MBB)

## Constitution precedence
- [.memory-bank/constitution.md](../constitution.md) is the top governing policy for agent decisions.
- MBB, spec-index, invariants, contracts, states, testing, and workflow docs refine the Constitution and MUST NOT contradict it.

## SSOT pyramid
- **Code**: WHAT/HOW — implementation truth.
- **Docstrings**: contracts + @docs pointers.
- **Memory Bank**: WHY/WHERE — boundaries, invariants, navigation.

## Hard rules
1. Every \`.memory-bank/**/*.md\` MUST have frontmatter with \`description:\`.
2. If a folder has >3 docs, add an \`index.md\` router.
3. Use annotated links: \`[.memory-bank/path](rel-path): короткое описание\`.
4. Atomic docs: one concept per doc; keep ~≤500 lines.
5. Duo docs remain valid: \`architecture/\` (WHAT/WHY) + \`guides/\` (HOW), cross-link both ways for concepts that use the classic pair model.
6. C4 layering: L1 product → L2 epics → L3 features → L4 plans/tasks.
7. Docs First: update MB immediately after finishing a task.
8. Refactor MB every 5–10 updates (split, merge, archive).
9. Separate facts from interpretations: mark hypotheses explicitly ("предположительно", "требует проверки").
10. After merge/rebase conflicts: re-check MB consistency.
11. MB-SYNC after each wave/significant change (see \`workflows/mb-sync.md\`).
12. When present, \`constitution.md\`, \`spec-index.md\`, \`glossary.md\`, \`invariants.md\`, \`contracts/*\`, \`states/*\`, \`runbooks/*\`, and \`testing/*\` act as an explicit normative layer and should be linked from relevant docs.

## Forbidden
- Copy-paste implementation details / pseudocode
- Duplicating configs instead of linking to source
- Speculative claims without evidence from code/metrics/tests

## Allowed / encouraged
- Invariants (MUST/NEVER)
- Contracts at boundaries
- Decision rationale + pointers
- Runbooks and verification procedures
`);

writeFile(`${MB}/spec-index.md`, `---
description: SDD Design Specs Index and route map for source-of-truth documents.
status: active
---
# SDD Design Specs Index

## Purpose
- Use this file as the route map for SDD design specs and explicit normative docs.
- Read this index before creating new specs or doing serious T2/T3 work.
- If a design area is not needed, mark it \`not_applicable\` with a short reason.
- Do not create authoritative specs unless PRD/user/spec evidence contains the decision.

## Hard rules
- Do not create a new spec before checking existing specs through this index.
- \`/spec-init\` may mark areas as planned/candidate/unknown/not_applicable, but must not invent authoritative architecture/contracts/states/data specs.
- \`/spec-backbone\` is optional after \`/prd\` and recommended/required when the feature set exposes shared T2/T3 backbone concerns; it routes shared backbone specs but does not replace per-feature \`/spec-design FT-<NNN>\`.
- \`/spec-design FT-<NNN>\` owns feature-level design before \`/prd-to-tasks FT-<NNN>\`.
- \`T2\` / \`T3\` tasks must carry relevant linked specs in task richer fields.

## Existing authoritative specs
- [.memory-bank/glossary.md](glossary.md): Термины и agreed vocabulary.
- [.memory-bank/invariants.md](invariants.md): Глобальные MUST/NEVER правила.
- [.memory-bank/constitution.md](constitution.md): Top governing policy for AI-first project decisions.
- [.memory-bank/contracts/](contracts/): Контракты интерфейсов и boundary specs.
- [.memory-bank/domains/](domains/): Domain/data model specs.
- [.memory-bank/states/](states/): Lifecycle/state rules.
- [.memory-bank/runbooks/](runbooks/): Operational procedures.
- [.memory-bank/testing/index.md](testing/index.md): Verification basis и quality gates.

## Planned design areas
- TBD

## Candidate design areas
- TBD

## Unknown design areas
- TBD

## Not applicable areas
- TBD

## Feature design status map
| Feature | spec_design_status | Linked specs | Notes |
|---|---|---|---|
| FT-XXX | unknown | - | Fill via /spec-design or /spec-auto; link backbone specs when /spec-backbone applies |

## Expected spec locations
- Feature hubs: \`.memory-bank/tech-specs/FT-<NNN>-<slug>.md\`
- Backbone/shared specs: \`.memory-bank/architecture/\`, \`.memory-bank/contracts/\`, \`.memory-bank/domains/\`, and \`.memory-bank/states/\`
- Architecture notes: \`.memory-bank/architecture/<topic>.md\`
- Contracts: \`.memory-bank/contracts/<boundary>.md\`
- Domain/data models: \`.memory-bank/domains/<domain>.md\`
- States: \`.memory-bank/states/<lifecycle>.md\`
- ADRs: \`.memory-bank/adrs/ADR-<NNN>-<slug>.md\`
- Testing/runbooks: \`.memory-bank/testing/\` and \`.memory-bank/runbooks/\`

## Gaps and open questions
- TBD

## Compatibility note
- Duo docs в \`architecture/\` и \`guides/\` остаются валидными.
- Этот слой уточняет source-of-truth, а не отменяет duo docs.
`);

writeFile(`${MB}/constitution.md`, `---
description: Project Constitution — governing principles for AI-first development.
status: active
version: 1
project_principles: framework-default
ratified: null
last_updated: ${TODAY}
---
# Project Constitution

## Purpose

This Constitution defines the non-negotiable principles that guide AI agents when planning, implementing, verifying, and synchronizing project work.

## Core Principles

### 0. Project Principles Status

This skeleton uses framework-default principles until \`/constitution\` runs the contextual interview. \`ratified: null\` means project principles are not ratified yet. When \`/constitution\` sets \`project_principles: ratified\` or \`project_principles: partial\`, it must fill \`ratified: YYYY-MM-DD\`. If the user explicitly skips that interview, keep or set \`project_principles: skipped\`, keep \`ratified: null\`, and continue; revisit \`/constitution\` later.

### I. AI-First Spec-Driven Development

Agents MUST derive implementation work from explicit product, requirement, feature, task, and workflow artifacts. Agents MUST NOT invent product scope without evidence or user instruction.

### II. Memory Bank Is Durable Project Knowledge

\`.memory-bank/\` is the durable source of project knowledge. Chat context is temporary. Agents MUST update Memory Bank after meaningful changes.

### III. Schema-Backed Task Execution

Tasks MUST use the current schema-backed JSON task record model. If the framework uses \`tier: T0|T1|T2|T3\`, agents MUST route execution and verification through that tier model.

### IV. Minimal Verifiable Change

Agents SHOULD prefer the smallest change that satisfies the task. Every completed task MUST have clear checks or evidence.

### V. Evidence Before Done

A task MUST NOT be marked done without verification evidence appropriate to its tier and scope.

### VI. No Legacy Fallback and No Speculation

Agents MUST NOT rely on deprecated task formats, old risk models, or undocumented assumptions. Unknowns MUST be recorded as blockers or explicit assumptions.

### VII. Context Discipline

Agents SHOULD read the smallest sufficient context for the task. Higher-tier or cross-cutting tasks MUST read relevant normative docs such as invariants, contracts, states, testing, and workflow policies.

### VIII. Synchronization

After meaningful changes, agents MUST synchronize affected Memory Bank docs, task state, changelog, and routing files.

## Governance

- Constitution has precedence over workflow habits and generated plans.
- MBB, spec-index, invariants, contracts, states, testing, and workflow docs refine this Constitution; they must not contradict it.
- Amendments must include rationale and update affected docs if needed.
- Constitution should stay short. Put concrete project rules into \`invariants.md\`, \`contracts/*\`, \`states/*\`, or workflow policy docs.

**Version**: 1 | **Ratified**: ${TODAY} | **Last updated**: ${TODAY}
`);

writeFile(`${MB}/glossary.md`, `---
description: Словарь терминов, сущностей и agreed vocabulary проекта.
status: draft
---
# Glossary

## Terms
- Term: definition

## Notes
- Используй этот файл для устранения неоднозначностей в названиях и статусах.
`);

writeFile(`${MB}/invariants.md`, `---
description: Глобальные инварианты и запреты проекта (MUST/NEVER).
status: draft
---
# Invariants

## MUST
- TBD

## NEVER
- TBD

## Notes
- Ссылайся на этот файл из архитектурных, контрактных и execution docs, если правило является cross-cutting.
`);

writeFile(`${MB}/product.md`, `---
description: Product brief (C4 L1): что это, для кого, core value, ограничения.
status: draft
---
# Product

## What this is

## Core value

## Audience

## Primary user flow

## Constraints
- Tech stack:
- Timeline:
- Non-goals:
`);

writeFile(`${MB}/requirements.md`, `---
description: Требования (REQ-IDs) + traceability matrix (RTM).
status: draft
---
# Requirements

## Status model
- Document \`status\`: \`draft|active|deprecated|archived\`
- RTM \`Lifecycle\`: \`planned|implemented|verified\`

## REQ list
- (fill from PRD; do not invent requirements without evidence)

## Out of scope
- ...

## Traceability (RTM)
| REQ | Epic | Feature | Test | Lifecycle |
|---|---|---|---|---|
| REQ-XXX | EP-XXX | FT-XXX | test:... | planned |
`);

writeFile(`${MB}/schemas/task.schema.json`, `${JSON.stringify(TASK_SCHEMA, null, 2)}\n`);

writeFile(`${MB}/tasks/index.json`, `${JSON.stringify(TASK_INDEX, null, 2)}\n`);

writeFile(`${MB}/testing/index.md`, `---
description: Стратегия тестирования и верификации (quality gates, anti-cheat, UI/e2e).
status: active
---
# Testing & Verification

## Quality gates
- lint / typecheck
- unit tests
- integration tests (if applicable)
- e2e tests for critical user flows

## UI verification
- Prefer Playwright / agent-browser / CDP for UI flows when available
- Store screenshots/videos/traces in .tasks/TASK-XXX/
- In Memory Bank keep only links + short conclusions

## Artifacts
- screenshots/logs/videos → .tasks/TASK-XXX/
- in Memory Bank store only links + conclusions
`);

writeFile(`${MB}/skills/index.md`, `---
description: Реестр доступных скиллов (когда применять) в этом репозитории.
status: active
---
# Skills

## Installed
- cold-start

## When to use
- Bootstrap: cold-start / mb-init
- Optional Analysis: mb-analysis, then /analysis /brainstorm /brief when the idea is not ready for PRD
- Project principles: /constitution after /brief or existing PRD context, before /write-prd only when project_principles is not ratified|partial
- PRD → MB: /write-prd, /spec-init, /prd, optional /spec-backbone, /spec-design, then /prd-to-tasks
- SDD design: /spec-init for route map, /spec-backbone for shared T2/T3 backbone concerns after /prd, /spec-design FT-XXX for manual feature design, /spec-auto for autonomous design
- Map codebase: /map-codebase
- Execution: /execute
- Verification (UAT): /verify
- Semantic adversarial verification: /red-verify
- Autonomous run: autonomous / autopilot
- Readiness doctor: mb-doctor
- Review: /review
- Maintenance: mb-garden
- Harness: mb-harness
`);

writeFile(`${MB}/changelog.md`, `---
description: Лог изменений Memory Bank.
status: active
---
# Changelog

## [${TODAY}] Initial setup
- Created Memory Bank skeleton
- Seeded core docs (product, requirements, testing, task registry)
`);

writeFile(`${MB}/workflows/mb-sync.md`, `---
description: Чеклист синхронизации Memory Bank после wave/изменений.
status: active
---
# MB-SYNC Checklist

- [ ] Duo docs consistent where the classic pair model is used (architecture ↔ guides)
- [ ] Optional normative docs, if present, are linked and do not contradict duo docs
- [ ] RTM lifecycle up to date (requirements.md)
- [ ] Feature/epic document \`status\` and implementation \`lifecycle\` are both updated
- [ ] JSON task records and \`.memory-bank/tasks/index.json\` updated
- [ ] Changelog entry added
- [ ] index.md links valid
- [ ] Lint passes (0 errors; blocking in autonomous mode)
`);

copyWorkflowReference('tier-policy.md');

writeFile(`${MB}/workflows/autonomy-policy.md`, `---
description: Guardrails and terminal states for unattended autonomous runs.
status: active
---
# Autonomy policy

## Default mode
- Prefer interactive mode unless the user explicitly requested unattended execution.

## Hard-stop categories
- security / compliance ambiguity
- external contracts or partner APIs with unknown behavior
- destructive data migrations
- secret reads / prod writes / deploys

## Allowed assumptions
- naming / wording / non-critical UX defaults
- low-impact implementation details that can be verified later

Non-blocking gaps must be written as explicit assumptions in \`.protocols/AUTONOMOUS-RUN/decision-log.md\`.

## Required gates
- latest \`/review\` verdict must be \`APPROVE\`
- mandatory \`/mb-doctor --strict\` before autonomous/autopilot task selection, after \`/mb-sync\` before promotion, and before final success
- tier-appropriate verification per TASK:
  - T0/T1: compact evidence may be enough
  - Scheduler mode T2/T3: \`/verify\` PASS and \`/red-verify\` semantic-pass are required before scheduler marks done
  - Manual mode: \`/verify\` PASS may close; \`/red-verify\` may run later and reopen/block/fail
  - T3: human-aware checkpoint plus rollback/recovery note are required
- mandatory \`/mb-sync\`
- mandatory lint/link consistency before final success, covered by \`mb-doctor\`

## Failure budgets
- max_retries_per_task: 2
- max_consecutive_failures: 3
- max_open_blockers: 3

## Terminal states
- \`SUCCESS\`
- \`HALT_BLOCKING_QUESTIONS\`
- \`HALT_CLARIFICATION_REQUIRED\`
- \`HALT_REVIEW_REJECT\`
- \`HALT_FAILURE_BUDGET\`
- \`HALT_DEPENDENCY_DEADLOCK\`
- \`HALT_POLICY_VIOLATION\`
- \`HALT_QUALITY_GATES\`
- \`HALT_BUDGET_EXCEEDED\`
`);

writeFile(`${MB}/workflows/execute-loop.md`, `---
description: Workflow: PRD → FT → TASK loop (interactive or autonomous).
status: active
---
# Execute loop (PRD → Feature → Tasks)

## Principle: no task explosion
- \`/prd\` creates L1–L3 only (product/requirements/epics/features/testing/index).
- \`/write-prd\` = PRD-level ambiguity closure. \`/clarify-feature\` = optional feature-level ambiguity pass.
- \`/spec-init\` creates the SDD Design Specs Index after \`/write-prd\` and before \`/prd\`.
- \`/spec-backbone\` is an optional pass after \`/prd\` when multiple features share T2/T3 backbone concerns; it does not replace per-feature \`/spec-design\`.
- \`/spec-design FT-<NNN>\` completes or marks unnecessary feature-level design before task decomposition.
- Tasks are created **per feature** via \`/prd-to-tasks FT-<NNN>\` after \`/prd\` creates clear feature docs and SDD design status is ready.

## Interactive mode (you stay)
1) \`/analysis -> /brief\` when idea discovery is needed; use \`/brainstorm\` before \`/brief\` only for raw ideas
2) \`/constitution\` for contextual governing principles when \`.memory-bank/constitution.md\` is missing or \`project_principles\` is framework-default|skipped|missing; if principles are already ratified/partial, continue to \`/write-prd\`; if explicitly skipped, continue with framework-default/skipped principles
3) \`/write-prd\` (creates clarified .memory-bank/prd.md)
4) \`/spec-init\` (updates .memory-bank/spec-index.md route map)
5) \`/prd\` (fills L1–L3)
6) Optional \`/spec-backbone\` when the feature set exposes shared T2/T3 backbone concerns
7) Pick one top feature; use \`/clarify-feature FT-001\` only for explicit feature blockers
8) \`/spec-design FT-001\` (updates only needed SDD specs or marks not_required)
9) \`/prd-to-tasks FT-001\` (creates IMPL plan + TASK-* for this feature)
10) Run \`/mb-doctor\` when task records change; use \`/mb-doctor --strict\` before autonomous handoff
11) Execute tasks from \`.memory-bank/tasks/index.json\` and indexed \`*.task.json\` records one-by-one:
   - \`/execute TASK-001 -> /verify TASK-001 -> /red-verify TASK-001 for T2/T3 -> /mb-sync\`
12) After each wave: \`/review\` (fresh context)

## Autonomous end-to-end mode (start and leave)
1) \`/autonomous\`
2) command runs \`/write-prd -> /spec-auto --init -> /prd -> optional backbone design -> /spec-auto --all -> /prd-to-tasks --all\`, then schedules ready TASKs
3) run \`/mb-doctor --strict\` before scheduler execution; T2/T3 tasks without SDD spec links are blockers
4) each TASK runs in **fresh CLI sessions**
5) after each \`/mb-sync\`, run \`/mb-doctor --strict\` before promoting dependents
6) after each wave: \`/review\`
7) final success only if last review = \`APPROVE\`, \`/mb-doctor --strict\` passes, and no blocking tasks remain

## Autonomous executor only
If JSON task records already exist and review gate already passed, use:
- \`/autopilot\`

\`/autopilot\` must run \`/mb-doctor --strict\` before each task selection pass and after each \`/mb-sync\` before promotion.

Codex (implement, then verify when the tier requires a separate verifier):
~~~bash
codex exec --ephemeral --full-auto -m gpt-5.2-high \\
  'TASK_ID=TASK-123. Read AGENTS.md + task record + tier-policy. Use tier-appropriate .protocols/TASK-123/ state. Implement only scoped changes. Record evidence. Report → .tasks/TASK-123/TASK-123-S-IMPL-final-report-code-01.md.'

codex exec --ephemeral --full-auto -m gpt-5.2-high \\
  'TASK_ID=TASK-123. For T2/T3 only: read task record + tier-policy + full protocol + acceptance criteria. Fill .protocols/TASK-123/verification.md. Evidence → .tasks/TASK-123/. VERDICT: PASS/FAIL.'
~~~

Claude (implement, then verify when the tier requires a separate verifier):
~~~bash
claude -p --no-session-persistence --permission-mode acceptEdits --model opus \\
  'TASK_ID=TASK-123. Read AGENTS.md + task record + tier-policy. Use tier-appropriate .protocols/TASK-123/ state. Implement only scoped changes. Record evidence. Report → .tasks/TASK-123/TASK-123-S-IMPL-final-report-code-01.md.'

claude -p --no-session-persistence --permission-mode acceptEdits --model opus \\
  'TASK_ID=TASK-123. For T2/T3 only: read task record + tier-policy + full protocol + acceptance criteria. Fill .protocols/TASK-123/verification.md. Evidence → .tasks/TASK-123/. VERDICT: PASS/FAIL/NEEDS-CLARIFICATION.'
~~~

## Parallel vs sequential
- Independent tasks (no shared files) MAY run in parallel (separate sessions).
- Dependent or shared-file tasks MUST run sequentially: TASK-A (execute→tier-appropriate verify→red-verify if required→mb-sync) → TASK-B.
`);

writeFile(`${MB}/adrs/ADR-000-template.md`, `---
description: "ADR-000: Шаблон для архитектурных решений."
status: active
owner: architecture
last_updated: ${TODAY}
source_of_truth:
  - .memory-bank/adrs/ADR-000-template.md
---
# ADR-000: Template

## ADR Status
accepted

## Context
Используй этот файл как шаблон для новых ADR.
Копируй и заполняй: Status, Context, Decision, Consequences, Alternatives.

## Decision
Каждое значимое архитектурное решение фиксируется как ADR в этой папке.

## Consequences
Все решения трассируемы и reviewable.
`);

console.log('\n[3/5] Writing command specs (SSOT templates)...');
const commandMetas = seedCommandsFromTemplates();

console.log('\n[4/5] Writing runtime scripts and creating symlinks...');
copyRuntimeScripts();
symlinkOrCopy('AGENTS.md', 'CLAUDE.md');
symlinkOrCopy('AGENTS.md', 'GEMINI.md');

// Native skills for Claude Code, Codex CLI, and OpenCode
// .claude/skills/  → Claude Code + OpenCode
// .agents/skills/  → Codex CLI + OpenCode
// Both are thin proxies pointing to .memory-bank/commands/ (SSOT)
console.log('\n[5/5] Creating native skills (proxy commands)...');

const commands = commandMetas;

const skillContent = (name, desc) =>
`---
name: ${name}
description: ${yamlQuote(desc)}
---
${GENERATED_MARKER}

Read and follow the instructions in \`.memory-bank/commands/${name}.md\`
`;

const expectedCommandNames = new Set(commands.map(({ name }) => name));
cleanupGeneratedProxySkills('.claude/skills', expectedCommandNames);
cleanupGeneratedProxySkills('.agents/skills', expectedCommandNames);

commands.forEach(({ name, desc }) => {
  // Claude Code + OpenCode
  ensureDir(`.claude/skills/${name}`);
  writeFile(`.claude/skills/${name}/SKILL.md`, skillContent(name, desc), { overwrite: SYNC_MODE });

  // Codex CLI + OpenCode
  ensureDir(`.agents/skills/${name}`);
  writeFile(`.agents/skills/${name}/SKILL.md`, skillContent(name, desc), { overwrite: SYNC_MODE });
});

console.log('\n[Done] Memory Bank skeleton initialized.');
console.log(`\nMemory Bank initialized in: ${ROOT}`);
